# Generated by Django 4.2.14 on 2024-10-01 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
